<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<CodeAnalysisRuleSet></CodeAnalysisRuleSet>
		<DocumentationFile>C:\Users\Peter\Source\Repos\ClassicBasic\ClassicBasic.Test\ClassicBasic.Test.xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<CodeAnalysisRuleSet></CodeAnalysisRuleSet>
		<DocumentationFile>C:\Users\Peter\Source\Repos\ClassicBasic\ClassicBasic.Test\ClassicBasic.Test.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.0.4" />
		<PackageReference Include="MSTest.TestFramework" Version="3.0.4" />
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Moq" Version="4.16.1" />
		<PackageReference Include="TestableIO.System.IO.Abstractions" Version="21.1.3" />
		<PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="21.1.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ClassicBasic.Interpreter\ClassicBasic.Interpreter.csproj" />
	</ItemGroup>

</Project>
